name: "Update ForkLineageOS"

on: { schedule: [{ cron: '0 0 */3 * *' }], workflow_dispatch }

jobs:
  updates:
    name: "Update ForkLineageOS"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210823_af94b54/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    # Update repo.json
    - run: nix develop -c ./flavors/lineageos/update.sh lineage-18.1
    # Update buildDateTime
    - run: sed -i "s/buildDateTime = mkDefault .*/buildDateTime = mkDefault $(date +%s);/" flavors/lineageos/default.nix
    - uses: EndBug/add-and-commit@v7.3.0
      with:
        author_name: Ilan Joselevich
        author_email: personal@ilanjoselevich.com
        message: 'ForkLineageOS: Update'
        add: '["flavors/lineageos/default.nix","flavors/lineageos/lineage-18.1"]'
